### ISSUE TITLE
[loop_closure_detection_node.py-3] rclpy.exceptions.InvalidParameterTypeException

### ISSUE THREAD

**Issue by talhassj28** [lajoiepy/cslam_experiments#10]
Hi,

I am trying to use cslam with the example Graco dataset in a docker container (ubuntu jammy with ros2 humble).
After changing the path for the bagfiles, I tried to launch with `ros2 launch cslam_experiments graco_lidar.launch.py`

The following errors occured:
- [loop_closure_detection_node.py-3] rclpy.exceptions.InvalidParameterTypeException: Trying to set parameter 'frontend.similarity_threshold' to '0.8' of type 'DOUBLE', expecting type 'NOT_SET'
[ERROR] [loop_closure_detection_node.py-3]: process has died ...
- [lidar_handler_node.py-4] rclpy.exceptions.InvalidParameterTypeException: Trying to set parameter 'frontend.pointcloud_topic' to 'pointcloud' of type 'STRING', expecting type 'NOT_SET'
[ERROR] [lidar_handler_node.py-4]: process has died

- log file: [launch.log](https://github.com/lajoiepy/cslam_experiments/files/12184083/launch.log)

I thought the problem is, that in loop_closure_detection_node.py and lidar_handler_node.py default values for parameters are set in the argument of `declare_parameters` in the second value of the tuples.
When the type of the yaml-file and the default value in the node don't match, this error occurs. (`None` results in `NOT_SET`)
So I think I fixed the problem at least for my usecase, by entering default values in with the right types int the python-files.

After that, I didn't receive the above mentioned errors and tried to use visualization with `ros2 launch cslam_visualization visualization.launch.py`, but could not see anything in rviz2.
log file after fix: [launch_after_fix.log](https://github.com/lajoiepy/cslam_experiments/files/12184164/launch_after_fix.log)

rviz2 screenshot:
![screenshot_rviz2](https://github.com/lajoiepy/cslam_experiments/assets/99833386/56df91ea-58a4-4d44-b436-1a8aaad48ce5)

I also tried to switch between all Fixed Frames in rviz but the result remained the same.
What am I doing wrong?

Thanks in advance for your help!

**Comment by lajoiepy** [comment]
Thanks for pointing out the parameter problem!
For your next problem, can you provide more info?
Can you run `rqt_graph` and share a screenshot? Look that all nodes all there, and try to find which topic is not published with `ros2 topic hz topic_name`

**Comment by talhassj28** [comment]
I tried to change the argument `robot_delay_s ` to 10.
The output of `ros2 topic list` changed as follows:
![output_topiclist2](https://github.com/lajoiepy/cslam_experiments/assets/99833386/99e81605-e872-4043-b966-a7ad0bb54572)

Seems like the second robot started to publish data. But the result in rviz2 remains the same.

**Comment by lajoiepy** [comment]
With the simulated rendez-vous, you need to wait until the robots are "activated" before they start to publish data. 
As a sanity check, can you try with only 1 simulated robot, disabling rendezvous. Even with only one robot should be able to see its output in rviz.

**Comment by talhassj28** [comment]
I figured out, that the problem occurs because the visualization_node cannot be executed.
Reason is that python packages like distinctipy or quaternion are missing.
Actually I thought I will install all dependent packages with rosdep, and with the requirements.txt-file in the main repo.
Is there anything I need to pay attention when installing dependencies?

**Comment by lajoiepy** [comment]
Not to my knowledge. Thanks for pointing out those missing dependencies in the requirements.txt!
