### ISSUE TITLE
Issue about the data experiments using kitti360

### ISSUE THREAD

**Issue by DioBakery** [lajoiepy/cslam_experiments#11]
The kitti360 structure is like this, I have also established the corresponding folder, how to use the 09 sequence for experiments?

<img width="373" alt="Snipaste_2023-09-26_10-07-59" src="https://github.com/lajoiepy/cslam_experiments/assets/69229972/5f331562-0aba-4ff5-9dd4-25ea50b373ad">

<img width="453" alt="Snipaste_2023-09-26_10-05-18" src="https://github.com/lajoiepy/cslam_experiments/assets/69229972/8b038545-de04-4bd4-afe4-660d06905c53">

**Comment by lajoiepy** [comment]
This is a KITTI360 dataset problem: https://github.com/autonomousvision/kitti360Scripts

Once you have a ROS1 bag convert it to ROS2 by playing it in ROS1 with a ROS1->ROS2 bridge https://github.com/ros2/ros1_bridge, and record in ROS2
