### ISSUE TITLE
How visualization result

### ISSUE THREAD

**Issue by HaynesLi** [lajoiepy/cslam_experiments#12]
Hi, after several months of stopping, I returned to this project again.

I can not visualize the result in RVIZ2. I used the following commands by others, but I still can not show the result.

Configuration:

I created the three folders named Graco-0, Graco-1 and Graco-2 under the /src/cslam_experiments/data/Graco_Ground/ , where I put my symlinks to the first three ROS2bags datasets that I downloaded from the GRACO datasets website (Ground-01, Ground-02 and Ground-03).
I also had to do the same in the /install/cslam_experiments/share/cslam_experiments/data/Graco_Ground/ folder to be able to run the experiment without errors of missing data.

Execution:

    I launch the simulation executing ros2 launch cslam_experiments graco_lidar.launch.py .

    I launch the visualization with ros2 launch cslam_visualization visualization.launch.py .

Result:

![Screenshot from 2024-03-27 16-25-15](https://github.com/lajoiepy/cslam_experiments/assets/86057371/2122d85a-f833-46ab-baf0-65973382897e)

**Comment by lajoiepy** [comment]
First you should use the lidar config https://github.com/lajoiepy/cslam_visualization/blob/main/config/lidar.rviz instead of the stereo config.

Can you post the terminal output of both commands?

**Comment by mjforan** [comment]
Obviously your problem is that rclpy cannot be imported. If you search that error on the internet you would find that you [need to deactivate your conda environment](https://robotics.stackexchange.com/questions/96239/ros2-modulenotfounderror-no-module-named-rclpy-rclpy).

**Comment by lajoiepy** [comment]
Yes rclpy import is the issue here. 
However for future reference, I now provide a Dockerfile example to simplify installation for users unfamiliar with ROS https://github.com/lajoiepy/cslam_experiments/tree/main/docker
I also have a minimal visualization (ony for lidar at the moment) using Rerun instead of RVIZ2 on this branch https://github.com/lajoiepy/cslam_visualization/tree/rerun_viz
