### ISSUE TITLE
numerical result analysis and map visualization

### ISSUE THREAD

**Issue by imjrl** [lajoiepy/cslam_experiments#13]
Hi, I am new to Swarm-SLAM framework. After several days of working, I ran the cslam_experiments preliminarily and got the wsl2 window display like this:
![屏幕截图 2024-03-31 021002](https://github.com/lajoiepy/cslam_experiments/assets/42366818/df070785-a7c3-402b-8124-2132f355d07a)
I ran the graco experiment on the Ubuntu 22.04 WSL2 environment, with two graco sequences placed on the /data folder:
![image](https://github.com/lajoiepy/cslam_experiments/assets/42366818/0cce217a-4cac-416b-992a-5be1d3805d37)
I wonder if this means everything is fine, and try to get the numerical locating the mapping result for further analysis. However, I have no idea about at which folder I can find the numerical result. 
what's more, there are some wrong with rviz2 on my WSL2, it got segment fault everytime when i try to launch it. so i wonder if there are other ways to visualize the result.

**Comment by lajoiepy** [comment]
Hi, thanks for your interest on our project!
Everything looks fine on the out put you get!
Currently RVIZ in the only way to visualize the map, and we don't have a map export format, but it should come soon :crossed_fingers: 
However, you can access the resulting pose graphs, which are published on a couple of topics that publishes https://github.com/lajoiepy/cslam_interfaces/blob/main/cslam_common_interfaces/msg/OptimizationResult.msg or https://github.com/lajoiepy/cslam_interfaces/blob/main/cslam_common_interfaces/msg/PoseGraph.msg .

By enabling the logs, and making sure you have a `results` folder, you should obtain pose graph file in the `.g2o` format (https://github.com/RainerKuemmerle/g2o) which can be visualized with their tool `g2o_viewer` tool.

**Comment by imjrl** [comment]
> Hi, thanks for your interest on our project! Everything looks fine on the out put you get! Currently RVIZ in the only way to visualize the map, and we don't have a map export format, but it should come soon 🤞 However, you can access the resulting pose graphs, which are published on a couple of topics that publishes https://github.com/lajoiepy/cslam_interfaces/blob/main/cslam_common_interfaces/msg/OptimizationResult.msg or https://github.com/lajoiepy/cslam_interfaces/blob/main/cslam_common_interfaces/msg/PoseGraph.msg .
> 
> By enabling the logs, and making sure you have a `results` folder, you should obtain pose graph file in the `.g2o` format (https://github.com/RainerKuemmerle/g2o) which can be visualized with their tool `g2o_viewer` tool.

thanks to your reply, that's greatly helpful!
but I still have questions about how to convert the OptimizationResult/PoseGraph data format into TUM format(time, tx, ty, tz, qx, qy, qz), in which (tx, ty, tz) refers to translation and (qx, qy ,qz, qw) refers to rotation.
is there any tool availble, or should I write a tool to convert it?

**Comment by lajoiepy** [comment]
Sorry for the delayed response. 
From the g2o files you can use the functions in this script https://gist.github.com/lajoiepy/10fb6a09ec23d09a85166bf8a641c7ee to convert to TUM format

**Comment by imjrl** [comment]
thanks a lot!

**Comment by HaiCLi** [comment]
> Hi, @HaiCLi in graco lidar experiments, please modify `/src/cslam_experiments/config/graco_lidar.yaml` to enable logs, and specify the log path with `log_folder` option in the `.yaml` file. as far as other experiments, please modify corresponding `.yaml` files. ![image](https://private-user-images.githubusercontent.com/42366818/387298857-12f7e172-6222-4fd0-8503-74f1bc0f1edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDU4MDMsIm5iZiI6MTczMjAwNTUwMywicGF0aCI6Ii80MjM2NjgxOC8zODcyOTg4NTctMTJmN2UxNzItNjIyMi00ZmQwLTg1MDMtNzRmMWJjMGYxZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MzgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Zjc1NjAwNDIxYmM5ZmM4ODUwYzA5NDcyZDk1MjBjMzVkM2I1NzJlN2RmYWZiOGE2MmFjOTAxYjdlNmI4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-risqXB095aHhRWezZ9eUtpFCQTLMZj5QikBXstWGaE)

Thanks bro

**Comment by HaiCLi** [comment]
![image](https://github.com/user-attachments/assets/c9d22b5b-40c7-4ff6-a705-5cae21e1cecc)

Hi, 
Did you meet the same problem when you use the g2o_view to view the "pose_graph.g2o"? Or I used same wrong setting?

Thanks!
