### ISSUE TITLE
SLAM trajectory alignment and evaluation

### ISSUE THREAD

**Issue by imjrl** [lajoiepy/cslam_experiments#15]
Hi there, thanks to your excellent work. 
I run the Swarm-SLAM on Euroc dataset. By enabling log option on <.yaml> file, I got the optimized result in a <.g2o> file.
However, after I convert the g2o file into tum format, I found the timestamp of poses in the tum file isn't the actual timestamp of the Euroc image frame.
So far, I get tum file like this:
> 18295873486192640 0.0164049 -0.102673 -0.0254598 0.0176008 0.019798 0.00492152 0.999637
18295873486192641 0.0128612 -0.0239119 -0.00257037 0.0106341 0.0161114 0.00504087 0.999801
18295873486192642 0.0112621 0.0447565 0.0174536 0.00404997 0.012451 0.00250701 0.999911
18295873486192643 0.0106312 0.146591 0.0442314 -0.0147657 0.0113923 0.000243831 0.999826
18295873486192644 0.00786497 0.208469 0.0536731 -0.0376361 0.00738803 0.00737722 0.999237
18295873486192645 0.00739252 0.234887 0.0580835 -0.048457 0.0070357 0.010076 0.99875
18295873486192646 0.00347129 0.312142 0.0561421 -0.0662902 -0.00453138 0.00174756 0.997789
18295873486192647 0.0021493 0.237049 0.0434951 -0.0628366 -0.00715272 5.86022e-05 0.997998
18295873486192648 0.00236645 0.174259 0.0331765 -0.0589377 -0.00180232 -0.00473162 0.998249
18295873486192649 0.0184909 -0.00117146 0.00835938 -0.0227052 0.0114345 -0.00400698 0.999669
18295873486192650 0.0216798 -0.0974182 -0.0123683 0.00714286 0.0210182 -0.0025743 0.99975
18295873486192651 0.0204848 -0.141432 -0.0273726 0.0188466 0.0219195 0.00168949 0.999581

You would find that the first column(timestamp) shows consecutive numbers, not the timestamp of the Euroc image frame.
I wonder if I could get a result tum file with the real timestamp of the Euroc image frame, so that I could use the [evo tool](https://github.com/MichaelGrupp/evo) to calculate ATE and APE metrics.
If not, is there any other way to  calculate ATE and APE metrics?
looking to your reply, thanks in advanced.

**Comment by lajoiepy** [comment]
Indeed, instead of the timestamp the ID corresponds to the (robot_id, keyframe_id). Here is a script to parse the IDs https://gist.github.com/lajoiepy/10fb6a09ec23d09a85166bf8a641c7ee

To know the mapping from (robot_id, keyframe_id) -> timestamp, I suggest logging the timestamps of your keyframes as they are generated in this function https://github.com/lajoiepy/cslam/blob/32527430ef271064d468f442a3ab754917abb011/src/front_end/rgbd_handler.cpp#L314
