### ISSUE TITLE
icp_odometry: Did not receive data since 5 seconds! Make sure the input topics are published

### ISSUE THREAD

**Issue by IacopoFornai** [lajoiepy/cslam_experiments#16]
hi! thank you for your great work, i have some trouble when launching the file, here it is what i did:

I'm trying to use the graco_lidar dataset launch file as is, in order to reproduce your simulation experiment with the ROS2bag provided.
The problem is that it seems like the ros2 bag doesn't have the ros2 topic on which icp_odometry node is subscribing

Configuration:

I created the three folders named Graco-0, Graco-1 and Graco-2 under the /src/cslam_experiments/data/Graco_Ground/ , where I put my symlinks to the first three ROS2bags datasets that I downloaded from the GRACO datasets website (Ground-01, Ground-03 and Ground-04).

Execution:

    I launch the simulation executing ros2 launch cslam_experiments graco_lidar.launch.py .

    I launch the visualization with ros2 launch cslam_visualization visualization.launch.py .

Results: i put some bash screen and my configuration of the launch file (that i have not modified since it seems ok as it is)

Thank you!

![Screenshot from 2024-10-23 15-53-44](https://github.com/user-attachments/assets/68b7f18c-f70f-4398-be4d-e45f4cd4cd53)
![Screenshot from 2024-10-23 15-51-03](https://github.com/user-attachments/assets/97bd33dd-cb3c-4a58-868d-37693470760f)
![Screenshot from 2024-10-23 15-50-50](https://github.com/user-attachments/assets/d55a7f90-9c34-4164-92f4-0d6fd337f7b0)
![Screenshot from 2024-10-23 15-49-55](https://github.com/user-attachments/assets/e030556d-faec-43d3-b524-06893fb03091)

**Comment by lajoiepy** [comment]
Hi! Make sure that the ros bag path, as shown in you screenshot, used to launch the bag is correct.
Another option is to comment out the bag play lines from the launch files, and launch the ros bags manually in another terminal.
Also, make sure that both the .db3 and metadata.yaml files are present in your ROS 2 bag folders.

**Comment by IacopoFornai** [comment]
thank you for your reply, i was missing the .yaml files in my ROS2 bag folders, nevertheless the same problem persists. running the ros2 bag and checking the topic i can't see /scan or /r0/pointcloud (i put a screen for it). Probably i don't know exactly how to modify the path to the rosbag symlinks in the launch file. For example: currently my symlink for ground-01 folder (where i have the.db3 and .yaml file) is inside /home/iacopo/Swarm-SLAM/src/cslam_experiments/data/Graco_Ground/Graco-0. how should i modify the path in the launch file?

![Screenshot from 2024-10-25 09-53-29](https://github.com/user-attachments/assets/8c86ea2e-53d0-4ee7-a60d-28b26c680f69)

**Comment by IacopoFornai** [comment]
i tried also using docker, i followed your guidelines trying to use the graco dataset lunch file in this way:

git clone https://github.com/lajoiepy/cslam_experiments.git
cd cslam_experiments/docker
make build
make cpu_run
make swarmslam-graco    (adding a docker exec to the makefile)

i kept the same configurations as the problem above : I created the three folders named Graco-0, Graco-1 and Graco-2 under the /src/cslam_experiments/data/Graco_Ground/ , where I put my symlinks to the first three ROS2bags datasets that I downloaded from the GRACO datasets website (Ground-01, Ground-03 and Ground-04).

but i'm getting some errors, can you please tell me what is the problem (i attach some screenshots)? Thank you in advance

![Screenshot from 2024-10-30 16-54-04](https://github.com/user-attachments/assets/37ea793a-b03c-4c84-a4ca-8fa478f1cb20)
![Screenshot from 2024-10-30 16-53-50](https://github.com/user-attachments/assets/1302c9fe-0d0e-4e18-aaa6-6fa228e34cbb)
![Screenshot from 2024-10-30 16-52-59](https://github.com/user-attachments/assets/4c5413aa-03e5-4ded-954f-cfef9ae9d35b)

**Comment by lajoiepy** [comment]
Bag launch problem: The symlink approach I suggest for the bags is entirely optional. I suggest hardcoding the path to your bags here: https://github.com/lajoiepy/cslam_experiments/blob/60208b56c0576c5b4b633ea91b696c95a8070663/launch/datasets_experiments/graco_lidar.launch.py#L81

Docker problem: It seems that something is wrong with the numpy version, which is very weird. Can you post the Dockerfile you built and the output of the make build command?

**Comment by IacopoFornai** [comment]
thanks for your help!
i think i solved the first problem, now i'm obtaining some reasonable outputs, just to be sure that everything is working properly i attach some screenshot of my results. sometimes in rviz /cslam/viz/pose_graph_markers goes to error state (i think when a new ros2bag is opening).

![Screenshot from 2024-11-06 10-04-23](https://github.com/user-attachments/assets/c8830add-2e7d-47dc-96c5-b866a8a02af1)
![Screenshot from 2024-11-05 18-10-42](https://github.com/user-attachments/assets/9fff4883-ad24-47aa-850b-49630f9ea66d)


i attach also the node list ,topic list and the terminal outputs, hope they can be useful if you find some problems

![Screenshot from 2024-11-05 18-09-21](https://github.com/user-attachments/assets/6258ee7c-0008-4500-9fb5-de3da7bf7565)
![Screenshot from 2024-11-05 18-09-18](https://github.com/user-attachments/assets/e8d76fd5-6541-41ed-ba84-0d65c404d3f7)
![Screenshot from 2024-11-05 18-09-07](https://github.com/user-attachments/assets/6806773b-8f1e-4fea-8a11-54313164f52d)

[experiment.txt](https://github.com/user-attachments/files/17645685/experiment.txt)
[visualization.txt](https://github.com/user-attachments/files/17645689/visualization.txt)

**Comment by IacopoFornai** [comment]
docker problem:
i built the docker file "dockerfile.lidar" that you provided without any changes
i attach the output of the make build command:

![Screenshot from 2024-11-06 11-42-39](https://github.com/user-attachments/assets/a1779f83-9a84-4110-a20c-c28fad3d3f44)
![Screenshot from 2024-11-06 11-42-43](https://github.com/user-attachments/assets/857626d7-615e-4236-bca7-bcdeb6f8b070)
