### ISSUE TITLE
real machine experiment

### ISSUE THREAD

**Issue by HaiCLi** [lajoiepy/cslam_experiments#17]
Hi,

I am a beginner in this area. Could you give some instructions on the real machine implementation in details?  Should I install this project on all robots or?  After I installed the drivers of each sensor, how could start this system? By the way, are there any 3D maps as output?

Thanks!

**Comment by lajoiepy** [comment]
Hi! Sorry for the delayed answer.
1. There are some start-up instructions here https://lajoiepy.github.io/cslam_documentation/html/md_startup_instructions.html
2. Yes you need to install the system on each robots.
3. Create or modify a launch file among those within this repository. You need to make sure the configuration fits with your robots.
4. Not directly, internally Swarm-SLAM builds a keyframe map, but this is not a good visualization of the environment. However, you can run the cslam_visualization module which will build a map based on Swarm-SLAM trajectory estimates. https://github.com/lajoiepy/cslam_visualization

**Comment by HerrSchnapps** [comment]
> Hi! Sorry for the delayed answer.
> 
>     1. There are some start-up instructions here https://lajoiepy.github.io/cslam_documentation/html/md_startup_instructions.html
> 
>     2. Yes you need to install the system on each robots.
> 
>     3. Create or modify a launch file among those within this repository. You need to make sure the configuration fits with your robots.
> 
>     4. Not directly, internally Swarm-SLAM builds a keyframe map, but this is not a good visualization of the environment. However, you can run the cslam_visualization module which will build a map based on Swarm-SLAM trajectory estimates. https://github.com/lajoiepy/cslam_visualization

Hi, 

What's the default exploring algorithm of this project(ROS2 Nav2)? I supposed this algorithm just contains perception, right?

Thanks!

**Comment by lajoiepy** [comment]
Yes it only contains perception. Nav2 is a great option, but you can use whichever you want.

**Comment by HerrSchnapps** [comment]
> Yes it only contains perception. Nav2 is a great option, but you can use whichever you want.

Thanks for your reply! I found a new question in my simulation environment. I did not find the transfer definition from "/velodyne/points to /r0/pointcloud". Could you tell me where is code definition? Thanks!
