### ISSUE TITLE
Lidar CSLAM with two turtlebot3

### ISSUE THREAD

**Issue by amine-chaabouni** [lajoiepy/cslam_experiments#8]
When simulating the interaction and cooperation of two turtlebot3 (waffle), the computation is not working out.
If we have two robots, `r0` and `r1`, the robot `r0` will be responsible for the [optimization](https://github.com/lajoiepy/cslam/blob/fd62c32e44c736c79b991c7d2d595766956313e9/src/back_end/decentralized_pgo.cpp#L347-L368).

For some reason, `r0` will always correctly compute its pose graph and will always set `r1`'s to nothing (no optimization done, the PoseGraphValues message is empty) and so, the pose graph of `r1` is not updated. When `r0` is not a neighbor anymore (simulated by killing the corresponding nodes), all the previous poses of `r1`are processed and the pose graph is updated.

Shouldn't the optimization still work even if there are no inter-robot loop closures? Is there a communication step that I'm missing? 

# Problem reproduction
execute the following commands:

1. `ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py` then destroy the turtlebot (as I spawned other ones)
2.  Spawn Two turtlebots 
```
ros2 run nav2_gazebo_spawner nav2_gazebo_spawner --robot_namespace turtlebot3_0 --robot_name waffle_0 --turtlebot_type waffle -x 0 -y 0.5
ros2 run nav2_gazebo_spawner nav2_gazebo_spawner --robot_namespace turtlebot3_1 --robot_name waffle_1 --turtlebot_type waffle -x -2 -y -0.5
```
3. Launch clsam
```
ros2 launch cslam_experiments cslam_lidar.launch.py max_nb_robots:=3
ros2 launch cslam_experiments cslam_lidar.launch.py max_nb_robots:=3 namespace:=/r1 robot_id:=1
```
4. Map the turtlebot3 outputs to the cslam inputs
[launch.txt](https://github.com/lajoiepy/cslam_experiments/files/10665014/launch.txt)
[remapper.txt](https://github.com/lajoiepy/cslam_experiments/files/10665015/remapper.txt)
```
ros2 launch my_webots remapper.launch.py real_robot_id:="'turtlebot3_0'"
ros2 launch my_webots remapper.launch.py real_robot_id:="'turtlebot3_1'" cslam_robot_id:="'r1'"
```
5. Launch visualization lidar `ros2 launch cslam_visualization visualization_lidar.launch.py`
6. Move the robots using the teleop
```
export TURTLEBOT3_MODEL=waffle && ros2 run turtlebot3_teleop teleop_keyboard --ros-args -r /cmd_vel:=/turtlebot3_0/cmd_vel
export TURTLEBOT3_MODEL=waffle && ros2 run turtlebot3_teleop teleop_keyboard --ros-args -r /cmd_vel:=/turtlebot3_1/cmd_vel
```

**Comment by lajoiepy** [comment]
Hi! Thanks for your interest in Swarm-SLAM!
I think you identified a corner case I did not considered.
I pushed a possible fix on this branch https://github.com/lajoiepy/cslam/tree/isolated_robot_optimization .
Can you tell me if this solves your issue?

**Comment by lajoiepy** [comment]
Also I am curious of how well the place recognition and registration will perform with the 2D laser scans converted to 3D pointclouds, let me know!

**Comment by amine-chaabouni** [comment]
Hi. Thank you for your quick response.
I just tested it and it solved the problem of individual slam. From what I am logging as debug messages, it seems that the robots are switching the optimizer role, which make it work (I don't think they should be doing that though, from what I understood from the code. I'll investigate this further another time)

As expected the place recognition is not amazing with 2D laser scans. Computing loop-closures seems inefficient as the number of inliers is quite low (6/100 on average).

**Comment by amine-chaabouni** [comment]
I have created two new launch files to automatically launch a demo with turtlebot3 (I use waffle). 
I have a remapper node that's just working as a remapper but can be used to change the data frm a LaserScan (if using LaserScan) to PointCloud2

It usually works fine (even though the number of inliers are not high enough to achieve loop-closures) but, in some cases [No sure reproduction scenario found yet], the optimizer of one or both robots gets stuck in the `OptimizerState::WAITING_FOR_NEIGHBORS_INFO` 
You can have a look of what I'm trying to achieve there if you find some time. I'll write to you again if I figure out either how to fix it or how to reproduce it.
Thank you.
