### ISSUE TITLE
Swarm-SLAM experiment reproduction with GRACO datasets

### ISSUE THREAD

**Issue by clmoro** [lajoiepy/cslam_experiments#9]
Hi,

I'm trying to use the `graco_lidar` dataset launch file as is, in order to reproduce your simulation experiment with the ROS2bag provided.
The problem is that my experiment seems to start correctly but with only one robot that performs SLAM.
I would appreciate if you could explain to me what I should expect as a result to verify if my installation is working properly and to understand better how to use your work.

**Configuration:**

I created the three folders named `Graco-0`, `Graco-1` and `Graco-2` under the `/src/cslam_experiments/data/Graco_Ground/` , where I put my symlinks to the first three ROS2bags datasets that I downloaded from the GRACO datasets website (Ground-01, Ground-02 and Ground-03).
I also had to do the same in the `/install/cslam_experiments/share/cslam_experiments/data/Graco_Ground/` folder to be able to run the experiment without errors of missing data.

**Execution:**

1. I launch the simulation executing `ros2 launch cslam_experiments graco_lidar.launch.py` .

2. I launch the visualization with `ros2 launch cslam_visualization visualization.launch.py` .

**Results:**

In the visualizer I can see that a map is being generated, but only for what concerns the first dataset. I see only the Graco-01 map construction on Rviz2.
Looking at the topics and the log files it seems that only the first robot `r0` is working, without exchanging information with the other robots that are not displaying any data.
In addition, the simulation never stops and a final map is not produced. Should I expect a different result?

Thank you!

**Comment by lajoiepy** [comment]
Hi!

Do you have the latest version of this repo? I removed the simulated rendez-vous by default (see this [commit](https://github.com/lajoiepy/cslam_experiments/commit/a4af757d9893a90d99a8755b19ed4f2638f3b93b) ) as explained [here](https://github.com/MISTLab/Swarm-SLAM/issues/5#issuecomment-1505236907).

This might be the problem, otherwise, can you post your terminal output in this thread?

**Comment by clmoro** [comment]
Hi!
Thanks for your reply.

It was exactly what you suggested to change, now everything seems to be working fine and all the nodes are activated for the three robots. Is it normal to have a simulation that lasts hours? Especially, the part related to the transmission of matches is not finishing, but no errors are displayed.

Moreover, I see this minor error message, that appears periodically only during the first part of the execution:

![error](https://user-images.githubusercontent.com/127135634/232881489-5ccf7012-6c95-406e-899b-c3d55b9691b7.png)

**Comment by lajoiepy** [comment]
Great!

Regarding your other questions:
1- No it is not normal, check that all nodes are still running. One might have crashed at a random moment and caused an undesirable side effect. Otherwise, check the heartbeats of all robots and if all topics are publishing properly, etc.
2- This error message is from the [RTAB-Map odometry](https://github.com/introlab/rtabmap_ros) which is external from Swarm-SLAM. That being said, this is fine as long as the odom ratio stays above 0. If the odometry becomes a problem, you can replace it with whatever odometry software that works for your system.

**Comment by clmoro** [comment]
Okay, I understand. Thank you.

I only have a further question: what should I expect as final result when the simulation ends?

**Comment by lajoiepy** [comment]
`Failed inter-robot loop closure measurement` means that the 3D registration between 2 keyframes failed. The inter-robot loop closure process is done in two steps: keyframes matching -> 3D registration -> loop closure measurement. There are parameters to control those steps, but it is essentially a trade-off game:
- [similarity_threshold](https://github.com/lajoiepy/cslam_experiments/blob/b6af98ef62a4abc294c32a234a2ce10cf5ad60c6/config/graco_lidar.yaml#L13) : Only pairs of keyframes with similarity higher than the threshold will be matched. If you increase the threshold you will get a better success ratio, but you will also get less matches in consequence.
- [registration_min_inliers](https://github.com/lajoiepy/cslam_experiments/blob/b6af98ef62a4abc294c32a234a2ce10cf5ad60c6/config/graco_lidar.yaml#L8) : Number of matching points between two pointclouds to be considered a success. If you decrease this threshold, you will get more successes, but there is a higher likelihood that some of the computed loop closures are outliers.

During and after the dataset run, you will get multiple outputs that you can visualize with [cslam_visualization](https://github.com/lajoiepy/cslam_visualization).
In particular, you will get [pose graph estimates](https://github.com/lajoiepy/cslam/blob/fd62c32e44c736c79b991c7d2d595766956313e9/src/back_end/decentralized_pgo.cpp#L169).

**Comment by clmoro** [comment]
Hi!

As you kindly suggested, I tried to run again the dataset experiment multiple times, but the simulation always falls in the above mentioned loop while transmitting matches, without improving further the pose graph estimate.

I can post here the last complete visualization:

![VISUALIZATION](https://user-images.githubusercontent.com/127135634/233776672-2cdceb66-1a2c-467c-9ac4-514962d30bd2.png)

From now on, the pose graph estimate is always the same, in particular, after a while the blue part of the pose graph is only displayed without changes.
Indeed, I checked the heartbeats of all robots and noticed that `/r0` and `/r1` are not publishing anymore at the moment described above, I don't know why.

**Comment by lajoiepy** [comment]
Ok thanks for the follow-up. The heartbeat stopping indicates that something is wrong. Maybe there is a bug or something that makes the neihbour manager crash. If you run `ros2 node list` at the end do you see all the nodes you launched?

If not, please scroll through the terminal output and search for the `process has died` message. There is a good chance that the error message will give us a lead on the bug. 

You can comment out other prints in the code if the message is too hard to find. Running the node in a debugger is also a good option.

**Comment by clmoro** [comment]
Thank you again for your kind reply.

I noticed that, when I ran the dataset, the simulation seems to crash at random every time around slightly different results.

Looking at the terminal output, the `pose graph manager` node crashes at a certain point:

![FINALPGMERROR](https://user-images.githubusercontent.com/127135634/233852359-6723d76f-bf55-4587-9484-1f30d52489f8.png)

**Comment by clmoro** [comment]
Hi,

It seems very reasonable, I will play a bit with these parameters and hope to solve.
I really appreciate your help. Thank you very much!
